### ISSUE TITLE
Exception when removing a document on a text indexed collection

### ISSUE THREAD

**Issue by angelix** [dizitart/nitrite-database#114]
Doing collection.remove(doc) on an Text indexed collection sometimes i get the following exception.
Nitrite 3.1.0

```
    java.lang.IllegalArgumentException: The value may not be null [1.4.197/0]
        at org.h2.mvstore.DataUtils.newIllegalArgumentException(DataUtils.java:844)
        at org.h2.mvstore.DataUtils.checkArgument(DataUtils.java:831)
        at org.h2.mvstore.MVMap.put(MVMap.java:119)
        at org.dizitart.no2.store.NitriteMVMap.put(NitriteMVMap.java:89)
        at org.dizitart.no2.internals.NitriteTextIndexingService.deleteIndex(NitriteTextIndexingService.java:73)
        at org.dizitart.no2.internals.IndexingService.removeIndexEntry(IndexingService.java:161)
        at org.dizitart.no2.internals.DataService.remove(DataService.java:227)
        at org.dizitart.no2.internals.NitriteService.remove(NitriteService.java:372)
        at org.dizitart.no2.internals.DefaultNitriteCollection.remove(DefaultNitriteCollection.java:360)
        at org.dizitart.no2.internals.DefaultNitriteCollection.remove(DefaultNitriteCollection.java:349)
        at org.dizitart.no2.internals.DefaultNitriteCollection.remove(DefaultNitriteCollection.java:335)
        at org.dizitart.no2.internals.DefaultNitriteCollection.remove(DefaultNitriteCollection.java:47)
```

**Comment by anidotnet** [comment]
Can you provide me some reproducible code?

**Comment by anidotnet** [comment]
Fix should be available in 3.2.0-SNAPSHOT

**Comment by angelix** [comment]
Hi @anidotnet,
when can we have the 3.2.0 as a regular release?

**Comment by anidotnet** [comment]
Soon. I hope I can release it by next week.
