### ISSUE TITLE
Error saving object with a _id  string field

### ISSUE THREAD

**Issue by ariel-lenis** [dizitart/nitrite-database#15]
Hi, currently i'm working with mongodb at the server side and nitrite for the client.

I'm trying to save a object from the server but the problem is that mongo manages the keys as strings like "592e4aa9ae0bb8df019a1155"

When i trying to save an object from a class that contains a string _id field, the insertion fails.

```
org.dizitart.no2.exceptions.InvalidIdException: NO2.6002: invalid _id found null
                                                                                    at org.dizitart.no2.Document.getId(Document.java:139)
                                                                                    at org.dizitart.no2.internals.DataService.insert(DataService.java:65)
                                                                                    at org.dizitart.no2.internals.NitriteService.insert(NitriteService.java:279)
                                                                                    at org.dizitart.no2.internals.DefaultNitriteCollection.insert(DefaultNitriteCollection.java:154)
                                                                                    at org.dizitart.no2.objects.DefaultObjectRepository.insert(DefaultObjectRepository.java:107)
```

Looks like a need to find a workaround to this, but maybe is a good idea to document this problem.

**Comment by ariel-lenis** [comment]
This was my workaround:

```
    @SerializedName("_id")
    @Id
    private String id;
```

**Comment by anidotnet** [comment]
This problem is very much database and it's driver software specific. As for example, the mongo driver and jongo handles id in a different manner. If you use jongo you would not face this problem, where as if you use mongo java driver, you would.

Anyway, the workaround you used is correct in this scenario.

**Comment by ariel-lenis** [comment]
Oh i see, thanks for the explanation!
