### ISSUE TITLE
Nitrite crash on Android API version less than 26

### ISSUE THREAD

**Issue by rainboy93** [dizitart/nitrite-database#163]
Hi,
Nitrite works find on all devices with Android API version from 26. But it always crashes with version down from 26.

Crash log:
```
java.lang.NoClassDefFoundError: java.time.Instant
        at com.fasterxml.jackson.datatype.jsr310.JSR310Module.<init>(JSR310Module.java:123)
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1208)
        at java.util.ServiceLoader$ServiceIterator.next(ServiceLoader.java:214)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:982)
        at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:966)
        at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1016)
        at org.dizitart.no2.mapper.JacksonFacade.createObjectMapper(JacksonFacade.java:83)
        at org.dizitart.kno2.KNO2JacksonFacade.createObjectMapper(KNO2JacksonFacade.kt:39)
        at org.dizitart.no2.mapper.JacksonFacade.createObjectMapper(JacksonFacade.java:95)
        at org.dizitart.no2.mapper.JacksonFacade.<init>(JacksonFacade.java:63)
        at org.dizitart.kno2.KNO2JacksonFacade.<init>(KNO2JacksonFacade.kt:36)
        at org.dizitart.kno2.KNO2JacksonFacade.<init>(KNO2JacksonFacade.kt:36)
        at org.dizitart.kno2.KNO2JacksonMapper.<init>(KNO2JacksonMapper.kt:33)
        at org.dizitart.kno2.Builder.createNitriteBuilder$potassium_nitrite(Builder.kt:132)
        at org.dizitart.kno2.BuilderKt.nitrite(Builder.kt:166)
        at vn.viettelpay.database.NitriteDb.getDb(NitriteDb.kt:17)
        at vn.viettelpay.contact.fetcher.ContactFetcher.getFromDb(ContactFetcher.kt:122)
        at vn.viettelpay.contact.fetcher.ContactFetcher$fetch$2$contacts$1.invokeSuspend(ContactFetcher.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

Please help me!

**Comment by anidotnet** [comment]
Please exclude the below transitive dependency for kno2 from gradle

`jackson-datatype-jsr310`

**Comment by rainboy93** [comment]
Hi there,
I just include these lines into gradle file but my application crash right after open.

```
implementation('org.dizitart:nitrite:3.2.0') {
        exclude group: "kno2", module: "jackson-datatype-jsr310"
    }
```

Sorry, I am quite newbie.
