### ISSUE TITLE
How to support embedded document for example List<MySubObject>  in an object which both implement Mappable?

### ISSUE THREAD

**Issue by rwsbillyang** [dizitart/nitrite-database#168]
In my project, a `List<MySubObject>` is embedded in an parent object `ComplexBean` which both implement `Mappable`, but app crashes when deserialize `ComplexBean`.

The sub-object is as below:
```
data class Tuple(var name: String? = null,var age: Int? = null): Mappable
{
    override fun write(mapper: NitriteMapper?) = Document().apply {
        Log.d("Nitrite","Tuple.write: " + this@Tuple.toString())
        name?.let { put("name",it) }
        age?.let { put("name",it) }
    }

    override fun read(mapper: NitriteMapper?, document: Document?) {
        document?.run {
            name = get("name") as String?
            age = get("age") as Int?
        }
        Log.d("Nitrite","Tuple.read, get "+this.toString())
    }
}
```
The parent object `ComplexBean` Kotin code:
```
data class ComplexBean(var myid: String, var level: Int? = null, var addr: Address? = null
         , var list: List<Tuple>? = null) : Mappable
{
    override fun write(mapper: NitriteMapper?) = Document().apply {
        Log.d("Nitrite","ComplexBean.write: "+ this@ComplexBean.toString())
        put("myid",myid)
        level?.let { put("level",it) }
        addr?.let { put("addr",it.write(mapper)) }
        list?.let { put("list",it)  }
    }

    override fun read(mapper: NitriteMapper?, document: Document?) {
        document?.run {
            myid = get("myid") as String
            addr= get("addr")?.run {  Address().apply { this.read(mapper,this@run as Document) }}
            level = get("level") as Int?
            list = get("list") as List<Tuple>?
        }
        Log.d("Nitrite","ComplexBean.read, get "+ this.toString())
    }
}
```

As above, in ComplexBean, I added `put` call in `write` method for list:
```
list?.let {put("list",it)  }
```
and added `get` in `read` method for list:
```
 list = get("list") as List<Tuple>?
```

when query ComplexBean after add it in MainActivity:
```
   private fun readComplexBean(){
       val str = repository2!!.find().toList().map { it.toString() }.joinToString("; ")
        Log.d("Nitrite",str)
        Toast.makeText(this,str,Toast.LENGTH_LONG).show()
    }
```
the app crashes and complaints:

> org.dizitart.no2.exceptions.NitriteIOException: NO2.2004: store is closed
        at org.dizitart.no2.internals.DefaultNitriteCollection.checkOpened(DefaultNitriteCollection.java:394)
        at org.dizitart.no2.internals.DefaultNitriteCollection.find(DefaultNitriteCollection.java:209)
        at org.dizitart.no2.objects.DefaultObjectRepository.find(DefaultObjectRepository.java:182)

The another embedded object Address in ComplexBean is ok.

Is my usage wrong? what's the correct how-to?

Thanks in advance.

The test complete code is from your official example but written in Kotlin, see  https://github.com/rwsbillyang/NitriteDemo

**Comment by anidotnet** [comment]
Sorry for late response. Your example code is not in working condition. It is not buildable as is and I could not spend more time to work on it.

I have took out the relevant code as follows

```kotlin
fun main() {
    val complexBean = ComplexBean("anidotnet", 1, Address("some street", "000000"), listOf(Tuple("Anindya Chatterjee", 0)))
    val complexBean2 = ComplexBean("anidotnet", 2, Address("some street", "000000"), listOf(Tuple("Anindya Chatterjee", 0)))

    val db = nitrite {
        path = "/tmp/kno2/test.db"
    }

    val repo = db.getRepository(ComplexBean::class.java)
    repo.insert(complexBean)
    repo.insert(complexBean2)

    println(repo.find().toList().joinToString("; ") { it.toString() })
}

data class Tuple(var name: String? = null, var age: Int? = null) : Mappable {
    override fun write(mapper: NitriteMapper?) = Document().apply {
        println("Tuple.write: " + this@Tuple.toString())
        name?.let { put("name", it) }
        age?.let { put("name", it) }
    }

    override fun read(mapper: NitriteMapper?, document: Document?) {
        document?.run {
            name = get("name") as String?
            age = get("age") as Int?
        }
        println("Tuple.read, get $this")
    }
}

data class ComplexBean(
    var myid: String, var level: Int? = null, var addr: Address? = null
    , var list: List<Tuple>? = null
) : Mappable {
    override fun write(mapper: NitriteMapper?) = Document().apply {
        println("ComplexBean.write: " + this@ComplexBean.toString())
        put("myid", myid)
        level?.let { put("level", it) }
        addr?.let { put("addr", it.write(mapper)) }
        list?.let { put("list", it) }
    }

    override fun read(mapper: NitriteMapper?, document: Document?) {
        document?.run {
            myid = get("myid") as String
            addr = get("addr")?.run { Address().apply { this.read(mapper, this@run as Document) } }
            level = get("level") as Int?
            list = get("list") as List<Tuple>?
        }
        println("ComplexBean.read, get $this")
    }
}

data class Address(var street: String? = null, var zip: String? = null) : Mappable {
    override fun write(mapper: NitriteMapper?) = Document().apply {
        street?.let { put("street", it) }
        zip?.let { put("zip", it) }
    }

    override fun read(mapper: NitriteMapper?, document: Document?) {

        document?.run {
            street = get("street") as String?
            zip = get("zip") as String?
        }
    }
}
```
& gradle.build as follows:

```gradle
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.31'
}

group 'org.dizitart.demo'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation('org.dizitart:potassium-nitrite:3.2.0')
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

I could not reproduce the issue you are facing. Here is the output I am getting

```
ComplexBean.write: ComplexBean(myid=anidotnet, level=1, addr=Address(street=some street, zip=000000), list=[Tuple(name=Anindya Chatterjee, age=0)])
ComplexBean.write: ComplexBean(myid=anidotnet, level=2, addr=Address(street=some street, zip=000000), list=[Tuple(name=Anindya Chatterjee, age=0)])
ComplexBean.read, get ComplexBean(myid=anidotnet, level=1, addr=Address(street=some street, zip=000000), list=[Tuple(name=Anindya Chatterjee, age=0)])
ComplexBean.read, get ComplexBean(myid=anidotnet, level=2, addr=Address(street=some street, zip=000000), list=[Tuple(name=Anindya Chatterjee, age=0)])
ComplexBean(myid=anidotnet, level=1, addr=Address(street=some street, zip=000000), list=[Tuple(name=Anindya Chatterjee, age=0)]); ComplexBean(myid=anidotnet, level=2, addr=Address(street=some street, zip=000000), list=[Tuple(name=Anindya Chatterjee, age=0)])
```

I guess, the issue is not with nitrite. Due to some other error in your app the nitrite db is getting closed and that's why you are getting this message. So I would say, the way you are implementing `Mappable` in your object is not wrong and it is not the source of this error.

**Comment by anidotnet** [comment]
According to the error stacktrace you mentioned,

>org.dizitart.no2.exceptions.NitriteIOException: NO2.2004: store is closed
at org.dizitart.no2.internals.DefaultNitriteCollection.checkOpened(DefaultNitriteCollection.java:394)
at org.dizitart.no2.internals.DefaultNitriteCollection.find(DefaultNitriteCollection.java:209)
at org.dizitart.no2.objects.DefaultObjectRepository.find(DefaultObjectRepository.java:182)

the store is already closed when you call `find` method. There is a check in place to see if the store is opened before find operation - https://github.com/dizitart/nitrite-database/blob/b2830347b68f023478a2ac9d2c6b80f6d15442a6/nitrite/src/main/java/org/dizitart/no2/internals/DefaultNitriteCollection.java#L209

**Comment by rwsbillyang** [comment]
@anidotnet, thank you very much for your detailed reply. The difference of the demo code between us is the app platform. I used Android, maybe the issue is android platform related or my app related.  

If I have time, I'll test it in your official example code in java.
