### ISSUE TITLE
java.lang.NullPointerException when calling repository.find

### ISSUE THREAD

**Issue by dustin-auby** [dizitart/nitrite-database#177]
Hi,

I am getting a null point exception when listing records. the error occurred on on a windows i3 laptop and i cannot replicate the issue on my computer. however it happens all the time on that i3 computer. if i copy that database and try run the program on my PC it throws the error so if i send you the database you will be able to see what is going on. the error seems to throw on the bellow piece of code, it seems to try and get a null document but if you inspect the list of documents none of them are null. this code is directly in the library and i inspected it using intelij idea debugger. the bold piece is where the null document occurs. this code is in the SearchService class.

```java
while(var6.hasNext()) {
                NitriteId id = (NitriteId)var6.next();
                **Document document = (Document)this.underlyingMap.get(id);**
                Object value = DocumentUtils.getFieldValue(document, sortField);
                if (value != null) {
                    if (value.getClass().isArray() || value instanceof Iterable) {
                        throw new InvalidOperationException(ErrorMessage.UNABLE_TO_SORT_ON_ARRAY);
                    }

                    if (sortedMap.containsKey(value)) {
                        List<NitriteId> idList = (List)sortedMap.get(value);
                        idList.add(id);
                        sortedMap.put(value, idList);
                    } else {
                        List<NitriteId> idList = new ArrayList();
                        idList.add(id);
                        sortedMap.put(value, idList);
                    }
                } else {
                    nullValueIds.add(id);
                }
            }
```

`
java.lang.NullPointerException
	at org.dizitart.no2.util.DocumentUtils.getFieldValue(DocumentUtils.java:80)
	at org.dizitart.no2.internals.SearchService.sortIdSet(SearchService.java:152)
	at org.dizitart.no2.internals.SearchService.setFilteredResultSet(SearchService.java:137)
	at org.dizitart.no2.internals.SearchService.find(SearchService.java:99)
	at org.dizitart.no2.internals.NitriteService.find(NitriteService.java:336)
	at org.dizitart.no2.internals.DefaultNitriteCollection.find(DefaultNitriteCollection.java:200)
	at org.dizitart.no2.objects.DefaultObjectRepository.find(DefaultObjectRepository.java:203)
`

**Comment by anidotnet** [comment]
If your stacktrace is correct, then the line number does not corresponds to the latest code. Could you please take the latest version of nitrite and try?

Please provide a reproducible code (like how you are inserting data, index info, how you are querying etc.) The code you provided is of nitrite's code, that does not help much in debugging. I need different inputs and conditions under which the error occurs. Better to provide a reproducible code and the data file.

Did you try by deleting the data file and retry the code in your i3 laptop?

**Comment by dustin-auby** [comment]
ok i have updated to the new database and its still having the issue. if i delete the database and start again it works but eventually hits the same issue. Something i have found is that it breaks on a certain id each time in this case 1451049180616 but if i list all objects in the repository this id does not exist. where would it be getting the id from. i will get more detailed code and post it.

**Comment by dustin-auby** [comment]
ok so i have found that in the repository indices there is reference to that object id but the object does not exist

**Comment by anidotnet** [comment]
Please post your code if possible which reproduce this error.

**Comment by anidotnet** [comment]
Anymore update on this? Do you have any reproducible code for me to test?

**Comment by anidotnet** [comment]
Closing this issue due to inactivity. Feel free to reopen the issue if you face it again.
