### ISSUE TITLE
Exception: user map found unexpectedly

### ISSUE THREAD

**Issue by minhthanh3145** [dizitart/nitrite-database#182]
Hi, I am having difficulties opening a created database but got this error from calling #openAndCreate() without username and password. If I use #openAndCreate(username, password) then the exception will say that no username found in the database.

I inspected the source code and but found no valuable information. Do you have any idea how to resolve it ?

```
org.dizitart.no2.exceptions.SecurityException: NO2.7003: user map found unexpectedly
	at org.dizitart.no2.Security.openSecurely(Security.java:101)
	at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:440)
	at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:360)
	at thanhto.katalon.katalon_notes.controller.NitriteDatabaseController.getDatabase(NitriteDatabaseController.java:167)
	at thanhto.katalon.katalon_notes.controller.NitriteDatabaseController.openConnection(NitriteDatabaseController.java:152)
	at thanhto.katalon.katalon_notes.provider.ServiceProvider.getDatabaseService(ServiceProvider.java:56)
	at thanhto.katalon.katalon_notes.toolitem.KatalonNotesToolItemWithMenuDescription$2.widgetSelected(KatalonNotesToolItemWithMenuDescription.java:105)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4080)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3706)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.kms.katalon.core.application.Application.internalRunGUI(Application.java:154)
	at com.kms.katalon.core.application.Application.runGUI(Application.java:144)
	at com.kms.katalon.core.application.Application.start(Application.java:74)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

```

**Comment by anidotnet** [comment]
Can you please provide a reproducible code for this issue?

**Comment by minhthanh3145** [comment]
Since the time I opened this issue I identified the problem. The password for a database was incorrect in that a hyphen is wrongly typed into an underscore and consequently this exception appears. Essentially it's wrong credential, but this exception doesn't say so. I am having my hands full so I will try to give a reproducible piece of code this weekend.

**Comment by anidotnet** [comment]
I could not reproduce the error using the wrong password scenario as described here in the recent version of nitrite. I suggest you to use 3.3.0.
