### ISSUE TITLE
Class Def Not found error - org/h2/mvstore/MVStore$ChunkIdsCollector

### ISSUE THREAD

**Issue by ptheofan** [dizitart/nitrite-database#186]
Sometimes I get the following exception. The same error happens when running on Macos and Raspbian (built with maven, using [nitrite 3.2.0](https://mvnrepository.com/artifact/org.dizitart/nitrite/3.2.0)).

```
[Thread-1] INFO org.dizitart.no2.Nitrite - Nitrite database has been closed successfully.
[Thread-1] ERROR org.dizitart.no2.NitriteShutDownHook - Error while database shutdown
java.lang.NoClassDefFoundError: org/h2/mvstore/MVStore$ChunkIdsCollector
	at org.h2.mvstore.MVStore.collectReferencedChunks(MVStore.java:1450)
	at org.h2.mvstore.MVStore.freeUnusedChunks(MVStore.java:1407)
	at org.h2.mvstore.MVStore.compactMoveChunks(MVStore.java:1876)
	at org.h2.mvstore.MVStore.compactMoveChunks(MVStore.java:1854)
	at org.dizitart.no2.store.NitriteMVStore.compact(NitriteMVStore.java:64)
	at org.dizitart.no2.Nitrite.compact(Nitrite.java:245)
	at org.dizitart.no2.Nitrite.close(Nitrite.java:289)
	at org.dizitart.no2.NitriteShutDownHook.run(NitriteShutDownHook.java:40)
Caused by: java.lang.ClassNotFoundException: org.h2.mvstore.MVStore$ChunkIdsCollector
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:61)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:420)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	... 14 more
```

**Comment by anidotnet** [comment]
Could you please provide a reproducible code for me? For the time being you can disable the shutdown hook form `NitriteBuilder` and use your own method to close the database properly.

**Comment by anidotnet** [comment]
Could not reproduce this issue in recent version of nitrite. In recent version of nitrite (3.3.0), mvstore library has been upgraded.

Closing this issue due to inactivity. Please feel free to re-open this issue if you face it again.
