### ISSUE TITLE
Disable annotations

### ISSUE THREAD

**Issue by kbventus** [dizitart/nitrite-database#192]
I'm using Nitrite with Kotlin (+ Kotlin module with Jackson) and want to ignore annotations in my class when inserting it into the database:

```kotlin
Nitrite.builder()
        .compressed()
        .filePath("data.db")
        .openOrCreate().apply {
            (context.nitriteMapper as JacksonMapper).objectMapper
                .registerModule(KotlinModule())
                .configure(MapperFeature.USE_ANNOTATIONS, false)
        }
```

Storing classes works, but the deserialization always fails(error):

[qtp789653861-19] ERROR org.dizitart.no2.mapper.JacksonFacade - Error while converting document to object 
java.lang.IllegalArgumentException: Cannot construct instance of `xxxxxxxxx.util.User` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3751)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3669)
	at org.dizitart.no2.mapper.JacksonFacade.asObject(JacksonFacade.java:134)
	at org.dizitart.no2.mapper.GenericMapper.asObjectInternal(GenericMapper.java:53)
	at org.dizitart.no2.mapper.AbstractMapper.asObject(AbstractMapper.java:76)
	at org.dizitart.no2.objects.ObjectCursor$ObjectCursorIterator.next(ObjectCursor.java:116)
	at org.dizitart.no2.util.Iterables.toList(Iterables.java:63)
	at org.dizitart.no2.objects.ObjectCursor.toList(ObjectCursor.java:92)
	at xxxxxx.controller.AuthController.authenticate(AuthController.kt:31)
	at xxxxxx.AppKt$main$1$1$1.invoke(App.kt:14)
	at xxxxx.AppKt$main$1$1$1.invoke(App.kt)
	at xxxxxx.AppKt$sam$i$io_javalin_core_security_AccessManager$0.manage(App.kt)
	at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:116)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
	at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:123)
	at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.core.JavalinServer$start$httpHandler$1.doHandle(JavalinServer.kt:53)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `xxxxx.util.User` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3746)
	... 46 more
[qtp789653861-19] WARN io.javalin.Javalin - Uncaught exception
org.dizitart.no2.exceptions.ObjectMappingException: NO2.9002: Cannot construct instance of `xxxxxxx.util.User` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1]
	at org.dizitart.no2.mapper.JacksonFacade.asObject(JacksonFacade.java:140)
	at org.dizitart.no2.mapper.GenericMapper.asObjectInternal(GenericMapper.java:53)
	at org.dizitart.no2.mapper.AbstractMapper.asObject(AbstractMapper.java:76)
	at org.dizitart.no2.objects.ObjectCursor$ObjectCursorIterator.next(ObjectCursor.java:116)
	at org.dizitart.no2.util.Iterables.toList(Iterables.java:63)
	at org.dizitart.no2.objects.ObjectCursor.toList(ObjectCursor.java:92)
	at xxxxx.controller.AuthController.authenticate(AuthController.kt:31)
	at xxxxxx.AppKt$main$1$1$1.invoke(App.kt:14)
	at xxxxxx.AppKt$main$1$1$1.invoke(App.kt)
	at xxxxx.AppKt$sam$i$io_javalin_core_security_AccessManager$0.manage(App.kt)
	at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:116)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
	at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:123)
	at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.core.JavalinServer$start$httpHandler$1.doHandle(JavalinServer.kt:53)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.base/java.lang.Thread.run(Thread.java:834)

And my testing class(I need the annotations for the rest api):

```kotlin
@Indices(Index(value = "key", type = IndexType.Unique), Index(value = "email", type = IndexType.Unique))
class User(
    @Id
    val id: UUID,
    @JsonIgnore
    var key: String,
    var email: String,
    @JsonIgnore
    var password: String,

    @JsonProperty("first_name")
    var firstName: String,
    @JsonProperty("last_name")
    var lastName: String,
    var organization: String,
    var status: UserStatus,
    @JsonIgnore
    val createdAt: Date
)
```

**Comment by anidotnet** [comment]
Please use **potassium-nitrite** library instead of nitrite if you have not used that already. It is the kotlin extension of nitrite. `KotlinModule` is already registered there. Now for your question, I still could not get what annotations you are trying to avoid. In your test class, I see annotations. Could you please elaborate it more with some example on what you are trying to achieve?

Note: It is always the best practice to separate your entity from your domain model (rest api request/response). I see you have used `JsonIgnore` on key field and you are trying to create index on the same field in db.

**Comment by kbventus** [comment]
My idea was to save all fields of the object in the database like id, key, password, etc....

But when a user makes a request to the api, it should only return id, email (so not the password or other valuable fields).

How should I split it? Make two separate classes like `UserModel` and `User` for the api?

**Comment by anidotnet** [comment]
> How should I split it? Make two separate classes like UserModel and User for the api?

Exactly.
