### ISSUE TITLE
Exception when deleting documents

### ISSUE THREAD

**Issue by lahiruchandima** [dizitart/nitrite-database#196]
I got below exception when deleting documents

```
[Caused by org.dizitart.no2.exceptions.FilterException: NO2.4001: invalid AND filter
       at org.dizitart.no2.filters.AndFilter.apply(AndFilter.java:74)
       at org.dizitart.no2.objects.filters.AndObjectFilter.apply(AndObjectFilter.java:52)
       at org.dizitart.no2.internals.SearchService.find(SearchService.java:67)
       at org.dizitart.no2.internals.DataService.remove(DataService.java:211)
       at org.dizitart.no2.internals.NitriteService.remove(NitriteService.java:384)
       at org.dizitart.no2.internals.DefaultNitriteCollection.remove(DefaultNitriteCollection.java:360)
       at org.dizitart.no2.objects.DefaultObjectRepository.remove(DefaultObjectRepository.java:176)
       at org.dizitart.no2.objects.DefaultObjectRepository.remove(DefaultObjectRepository.java:170)
       at com.my.app.core.DatabaseHelper.removeOldReceipts(DatabaseHelper.java:630)
       at com.my.app.core.ApplicationEx.onCreate(ApplicationEx.java:194)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6162)
       at android.app.ActivityThread.access$1200(ActivityThread.java:235)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6990)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
	   
Caused by java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Negative position -3136; p=667128680214556, c=chunk:97b,block:7fffffffffffffff,len:7fffffff,liveMax:0,livePages:0,map:9,max:42c0,next:128,pages:a,root:25ec0000ad3c9,time:3fd23f080,unused:422f7251b,unusedAtVersion:a6e,version:97b,pinCount:0 [1.4.200/6]
       at java.util.concurrent.FutureTask.report(FutureTask.java:123)
       at java.util.concurrent.FutureTask.get(FutureTask.java:193)
       at org.dizitart.no2.filters.AndFilter.apply(AndFilter.java:60)
       at org.dizitart.no2.objects.filters.AndObjectFilter.apply(AndObjectFilter.java:52)
       at org.dizitart.no2.internals.SearchService.find(SearchService.java:67)
       at org.dizitart.no2.internals.DataService.remove(DataService.java:211)
       at org.dizitart.no2.internals.NitriteService.remove(NitriteService.java:384)
       at org.dizitart.no2.internals.DefaultNitriteCollection.remove(DefaultNitriteCollection.java:360)
       at org.dizitart.no2.objects.DefaultObjectRepository.remove(DefaultObjectRepository.java:176)
       at org.dizitart.no2.objects.DefaultObjectRepository.remove(DefaultObjectRepository.java:170)
       at com.my.app.core.DatabaseHelper.removeOldReceipts(DatabaseHelper.java:630)
       at com.my.app.core.ApplicationEx.onCreate(ApplicationEx.java:194)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6162)
       at android.app.ActivityThread.access$1200(ActivityThread.java:235)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6990)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
	   
Caused by java.lang.IllegalStateException: Negative position -3136; p=667128680214556, c=chunk:97b,block:7fffffffffffffff,len:7fffffff,liveMax:0,livePages:0,map:9,max:42c0,next:128,pages:a,root:25ec0000ad3c9,time:3fd23f080,unused:422f7251b,unusedAtVersion:a6e,version:97b,pinCount:0 [1.4.200/6]
       at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
       at org.h2.mvstore.Chunk.readBufferForPage(Chunk.java:345)
       at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1214)
       at org.h2.mvstore.MVStore.readPage(MVStore.java:2209)
       at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
       at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
       at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
       at org.h2.mvstore.MVMap$2$1.hasNext(MVMap.java:802)
       at org.dizitart.no2.filters.LesserThanFilter.matchedSet(LesserThanFilter.java:73)
       at org.dizitart.no2.filters.LesserThanFilter.apply(LesserThanFilter.java:66)
       at org.dizitart.no2.objects.filters.LessThanObjectFilter.apply(LessThanObjectFilter.java:59)
       at org.dizitart.no2.filters.BaseFilter$1.call(BaseFilter.java:60)
       at org.dizitart.no2.filters.BaseFilter$1.call(BaseFilter.java:56)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)](url)
```

Following is the code which deletes the documents

    public void removeOldReceipts() {
        long fromTimestamp = System.currentTimeMillis() - ReceiptCacher.MAX_RECEIPT_CACHE_DURATION;
        WriteResult removeResult = receiptRepository.remove(and(lt("createdTimestamp", fromTimestamp), eq("status", Receipt.Status.COMPLETED), eq("synced", true)));
        LOGGER.info("removeOldReceipts: Removed {} receipts older than {}", removeResult.getAffectedCount(), new Date(fromTimestamp));
    }

Please look into this.

**Comment by anidotnet** [comment]
It looks like data file is somehow corrupted. Unless I see the full code, it is very hard to determine the root cause of it.

**Comment by anidotnet** [comment]
Closing this issue for inactivity. If it resurfaces, please provide complete reproducible code.
