### ISSUE TITLE
Nitrite 3.3.0 getting Exception during find with ObjectRepository

### ISSUE THREAD

**Issue by Tanvir6364** [dizitart/nitrite-database#205]
Hello,
I have setup nitritedb 3.3.0 using maven. I am getting the following exception while trying to retrieve the example from the document provided:

```
java.lang.reflect.InvocationTargetException
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:567)
				at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
				at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:567)
				at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
			Caused by: java.lang.RuntimeException: Exception in Application start method
				at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
				at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
				at java.base/java.lang.Thread.run(Thread.java:830)
			Caused by: java.lang.IllegalArgumentException: Can not construct instance of database.NitriteDBConnection$Employer: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
			 at [Source: N/A; line: -1, column: -1]
				at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3580)
				at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3499)
				at org.dizitart.no2.mapper.JacksonFacade.asObject(JacksonFacade.java:134)
				at org.dizitart.no2.mapper.GenericMapper.asObjectInternal(GenericMapper.java:53)
				at org.dizitart.no2.mapper.AbstractMapper.asObject(AbstractMapper.java:76)
				at org.dizitart.no2.objects.ObjectCursor$ObjectCursorIterator.next(ObjectCursor.java:110)
				at org.dizitart.no2.util.Iterables.firstOrDefault(Iterables.java:48)
				at org.dizitart.no2.objects.ObjectCursor.firstOrDefault(ObjectCursor.java:81)
				at database.NitriteDBConnection.<init>(NitriteDBConnection.java:39)
				at database.NitriteDBConnection.getInstance(NitriteDBConnection.java:46)
				at Main.start(Main.java:15)
				at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
				at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
				at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
				at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
				at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
				at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
			Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of database.NitriteDBConnection$Employer: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
			 at [Source: N/A; line: -1, column: -1]
				at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
				at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1456)
				at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1012)
				at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1203)
				at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
				at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
				at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3575)
				... 16 more
			Exception running application Main
```

This is just plain example i tried from the document. But nothings working:

```java
        String dbFilesLocation = Paths.get("resources/db/").toAbsolutePath().toString();

	nitriteDb = Nitrite.builder()   // register java.time module
	                .filePath(dbFilesLocation + "/nitrite.db")
	                .openOrCreate("tanvir", "123456");

	ObjectRepository<Employer> repository = nitriteDb.getRepository(Employer.class);

	Employer emp = new Employer();
	emp.setEmpId(20365);
	emp.setName("John Doe");
	emp.setJoinDate("10-10-2020");
	        
	repository.insert(emp);

	Employer empployee = repository.find(ObjectFilters.eq("name", "John Doe"))
	                .firstOrDefault();

	System.out.println("Employee:" + empployee.getName());`

	private class Employer implements Serializable {
	        @Id
	        private long empId;
	        private String joinDate;
	        private String name;

	        public long getEmpId() {
	            return empId;
	        }

	        public void setEmpId(long empId) {
	            this.empId = empId;
	        }

	        public String getJoinDate() {
	            return joinDate;
	        }

	        public void setJoinDate(String joinDate) {
	            this.joinDate = joinDate;
	        }

	        public String getName() {
	            return name;
	        }

	        public void setName(String name) {
	            this.name = name;
	        }
	}
```

Any help would be highly appreciated.
Thanks

**Comment by anidotnet** [comment]
Make your `Employer` class public and try. Your issue was with jackson

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of database.NitriteDBConnection$Employer: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)`

**Comment by anidotnet** [comment]
Closing issue due to inactivity. Re-open the issue if you face this issue even after changing your code as suggested above.
