### ISSUE TITLE
SimpleStringProperty can't  be  deserialized

### ISSUE THREAD

**Issue by ylyxf** [dizitart/nitrite-database#210]
When use SimpleStringProperty  as POJO's property , the value can't be  deserialized . 
It seems the SimpleStringProperty was stored as a object when insert. Can i store Javafx Property field as it's Basic Type (SimpeStringProperty -> String , SimpleIntegerProperty -> Integer) ?

Error Stack
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: test.Employee["name"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3750)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3668)
	at org.dizitart.no2.mapper.JacksonFacade.asObject(JacksonFacade.java:134)
	at org.dizitart.no2.mapper.GenericMapper.asObjectInternal(GenericMapper.java:53)
	at org.dizitart.no2.mapper.AbstractMapper.asObject(AbstractMapper.java:76)
	at org.dizitart.no2.objects.ObjectCursor$ObjectCursorIterator.next(ObjectCursor.java:116)
	at test.Main.main(Main.java:34)
```
![document](https://user-images.githubusercontent.com/3871920/76209304-852b7900-623c-11ea-9684-b1b3b56b14f3.png)

this is the model :
```
package test;

import org.dizitart.no2.objects.Id;

import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;

public class Employee {

	@Id
	private String id;

	private SimpleStringProperty name = new SimpleStringProperty();

	private SimpleIntegerProperty age = new SimpleIntegerProperty();

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public final SimpleStringProperty nameProperty() {
		return this.name;
	}

	public final String getName() {
		return this.nameProperty().get();
	}

	public final void setName(final String name) {
		this.nameProperty().set(name);
	}

	public final SimpleIntegerProperty ageProperty() {
		return this.age;
	}

	public final int getAge() {
		return this.ageProperty().get();
	}

	public final void setAge(final int age) {
		this.ageProperty().set(age);
	}

}

```

and this is the test code 

```
package test;

import java.io.IOException;
import java.util.UUID;

import org.dizitart.no2.Nitrite;
import org.dizitart.no2.objects.Cursor;
import org.dizitart.no2.objects.ObjectRepository;

import com.fasterxml.jackson.databind.ObjectMapper;

public class Main {

	public static void main(String[] args) throws IOException {
		Employee employee = new Employee();
		employee.setId(UUID.randomUUID().toString());
		employee.setName("John");
		employee.setAge(21);

		ObjectMapper mapper = new ObjectMapper();
		String json = mapper.writeValueAsString(employee);

		System.out.println(json);

		Employee employeeRead = mapper.readValue(json, Employee.class);
		System.out.println(employeeRead.getId());
		System.out.println(employeeRead.getName());
		System.out.println(employeeRead.getAge());

		Nitrite db = Nitrite.builder().compressed().filePath("test.db").openOrCreate("sa", "sa");
		ObjectRepository<Employee> repository = db.getRepository(Employee.class);
		repository.insert(employee);
		Cursor<Employee> employeeList = repository.find();
		for (Employee emp : employeeList) {
			System.out.println(emp.getName());
		}
	}

}

```

**Comment by anidotnet** [comment]
You can implement `Mappable` in your pojo and store the value of the property instead of the actual property field.

https://www.dizitart.org/nitrite-database/#mappable

**Comment by ylyxf** [comment]
I’m developing a JavaFx applicaiton which will use a lot of  `javafx.beans.property.Property`  in beans.
all  the beans which include xxxProperty fields should implement Mappable interface ( or extends a base class that implement the Mappable  interface) .

I don't want to implement the Mappable  for every bean ,and it's a little hard for me to implement a common util method to  iterate document ( with it's children and grandchildren) and reflection values to dist object fields  ，which will called  in the method  ` public void read(NitriteMapper mapper, Document document)`   of Mappable .
 
so I track the code and  found in the   `JacksonFacade` ,the  objectMapper is initialized by `.withGetterVisibility(JsonAutoDetect.Visibility.NONE) ` and  `.withIsGetterVisibility(JsonAutoDetect.Visibility.NONE)` .

with this feature ,an SimpleStringProperty field  is serialized to 
```
"name":{"value":"John","observable":null,"listener":null,"valid":true,"helper":null,"bean":null,"name":""}
```
when i remove the feature , the SimpleStringProperty  is serialized to 
```
"name":"John"
```

so I change the objectMapper  after db initial:
```
Nitrite db = Nitrite.builder().compressed().filePath("test2.db").openOrCreate("sa", "sa");
		NitriteMapper nitriteMapper = db.getContext().getNitriteMapper();
		if (nitriteMapper instanceof JacksonMapper) {
			JacksonMapper JacksonMapper = (JacksonMapper) nitriteMapper;
			JacksonFacade jacksonFacade = (JacksonFacade) JacksonMapper.getMapperFacade();
			jacksonFacade.getObjectMapper()
					.setVisibility(objectMapper.getSerializationConfig().getDefaultVisibilityChecker()
							.withGetterVisibility(JsonAutoDetect.Visibility.DEFAULT)
							.withIsGetterVisibility(JsonAutoDetect.Visibility.DEFAULT)
							.withIsGetterVisibility(JsonAutoDetect.Visibility.NONE));
		}
```

 then i works for me .
