### ISSUE TITLE
unable to create collection named as "object"

### ISSUE THREAD

**Issue by adhamelia** [dizitart/nitrite-database#220]
@anidotnet 

We have a collection named "object" which creates a problem while opening the DB.  It seems like nitrite is a powerful DB but frequently we encounter issues regarding the nomenclature of field/collections etc...   we have to do many hook and crook to make it workable nitrite DB for us. but this time even not able to open the DB after creating "object" collection. 

Can we have a workaround or is there something that I can change the code itself ???

**Comment by anidotnet** [comment]
I am curious to know what kind of issue you are facing here. Do you have some reproducible code or stacktrace to share? I tried to recreate it according to your description but have not encountered any issue

```java
	@Test
    public void testIssue220() {
        NitriteCollection collection = db.getCollection("object");
        Document doc1 = createDocument("key", "key").put("second_key", "second_key").put("third_key", "third_key");
        Document doc2 = createDocument("key", "key").put("second_key", "second_key").put("fourth_key", "fourth_key");
        Document doc = createDocument("fifth_key", "fifth_key");

        collection.insert(doc1, doc2, doc);
        db.close();

        db = new NitriteBuilder()
            .filePath(fileName)
            .compressed()
            .openOrCreate("test-user", "test-password");
        collection = db.getCollection("object");
        Cursor documents = collection.find(Filters.eq("fifth_key", "fifth_key"));
        assertEquals(1, documents.size());
        assertEquals(doc, documents.firstOrDefault());
    }
```

Next thing you need to remember is every database has some reserved keywords for internal data structures, during design phase of your application you always need to consider those limitation.

**Comment by adhamelia** [comment]
my sample code. 

JDK 11 MAC OS

Nitrite Version : 3.4.1

`Nitrite db = Nitrite.builder()
                    .compressed()
                    .filePath("demo.db")
                    .openOrCreate("user", "password");

            NitriteCollection collection = db.getCollection("object");

            collection.drop();
            collection = db.getCollection("object");

            Document doc = new Document().put("name","john");

            collection.insert(doc);

            Cursor cursor = collection.find( and(eq("name", "john")));

            System.out.println(cursor.firstOrDefault());`


Stack Trace : 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: Object (wrong name: object)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.dizitart.no2.util.ObjectUtils.isObjectStore(ObjectUtils.java:189)
	at org.dizitart.no2.NitriteContext.dropCollection(NitriteContext.java:181)
	at org.dizitart.no2.internals.NitriteService.dropCollection(NitriteService.java:472)
	at org.dizitart.no2.internals.DefaultNitriteCollection.drop(DefaultNitriteCollection.java:233)
	at DBDemo.main(DBDemo.java:30)

Process finished with exit code 1

**Comment by adhamelia** [comment]
Steps to reproduce.

Run the sample, the first time it works after that run again the same program and you will get the error.

**Comment by anidotnet** [comment]
Sorry @adhamelia I can't reproduce this error on jdk11. Though I am using linux, I don't have any Mac OS. When looking into the stacktrace, I found something peculiar. The error is being thrown from the below code in nitrite.

```java
public static boolean isObjectStore(String collectionName) {
    try {
        if (isNullOrEmpty(collectionName)) return false;
        Class clazz = Class.forName(collectionName);
        return clazz != null;
    } catch (ClassNotFoundException e) {
        return isKeyedObjectStore(collectionName);
    }
}
```

If the class with `collectionName` is not found in classpath, it throws a `ClassNotFoundException` which is handled in the catch block, and here is the stack for that exception

```
java.lang.ClassNotFoundException: object
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.dizitart.no2.util.ObjectUtils.isObjectStore(ObjectUtils.java:189)
	at org.dizitart.no2.NitriteContext.dropCollection(NitriteContext.java:181)
	at org.dizitart.no2.internals.NitriteService.dropCollection(NitriteService.java:472)
	at org.dizitart.no2.internals.DefaultNitriteCollection.drop(DefaultNitriteCollection.java:233)
	at org.dizitart.no2.NitriteTest.testIssue220(NitriteTest.java:389)
```

Peculiar thing is according to jdk [document](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html#forName(java.lang.String)), `Class.forName` throws `java.lang.ClassNotFoundException` not `java.lang.NoClassDefFoundError`, which is happening in your case. 

What jdk are you using? Is it openjdk or some custom build? Can you try this in any other os?

**Comment by anidotnet** [comment]
Just another note, if you have initiated module system, just once disable it and test again.
