### ISSUE TITLE
java.nio issues with a lot of Android devices

### ISSUE THREAD

**Issue by iGio90** [dizitart/nitrite-database#35]
Hello! Im the android developer for StatsRoyale and an happy user of nitrite db for multiple projects.
Due to the amount of installs that StatsRoyale have (almost 500k) you can imagine that as well, the amount of problems that pop to light are a lot.

I would like to report this problem coming from a lot of different devices:

`Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
       at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:404)
       at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:313)
       at com.overwolf.statsroyale.DBController$1.run(DBController.java:60)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList[[zip file "/data/app/com.overwolf.statsroyale-1/base.apk"],nativeLibraryDirectories=[/data/app/com.overwolf.statsroyale-1/lib/arm, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:404)
       at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:313)
       at com.overwolf.statsroyale.DBController$1.run(DBController.java:60)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

nio is not inside any android prior to 7 or even 8 because got introduced with JDK 7 (Android still uses 6 as far as i know) but not everyone is getting the issue.. I would guess only certain probably due to manufacturer customizations.

Can we go for standard File instead?

**Comment by anidotnet** [comment]
Unfortunately it is not possible for me. It is not only the db builder, the main storage library **mvstore** is built on top of java nio apis. That is the reason why an android project, dependant on nitrite, must target jdk 1.7 and also should have minSdkVersion=15 and targetSdkVersion=24

**Comment by rwsbillyang** [comment]
In my android device with API 18:
```
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at org.h2.mvstore.MVStore.writeStoreHeader(MVStore.java:920)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:399)
```
java.nio.charset.StandardCharsets is added in API level 19, see https://developer.android.google.cn/reference/java/nio/charset/StandardCharsets.html

So minSdkVersion should be 19 or higher for android devices.
