### ISSUE TITLE
Error with java.nio.file.Paths

### ISSUE THREAD

**Issue by ariel-lenis** [dizitart/nitrite-database#4]
Hi,
I tried to create a simple application using nitrite:

- Updated gradle

- Created sample project with a simple db creation code

And after run the aplication i got this:

05-30 01:45:39.096 27695-27702/? E/art: Failed sending reply to debugger: Broken pipe
05-30 01:45:39.193 27695-27695/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.newtype.nitritetest, PID: 27695
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
                                                       at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:387)
                                                       at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:338)
                                                       at com.example.newtype.nitritetest.MainActivity.startDatabase(MainActivity.java:26)
                                                       at com.example.newtype.nitritetest.MainActivity.onCreate(MainActivity.java:18)
                                                       at android.app.Activity.performCreate(Activity.java:6705)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2664)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:241)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6217)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList[[zip file "/data/app/com.example.newtype.nitritetest-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.newtype.nitritetest-2/lib/arm64, /system/lib64, /vendor/lib64]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at org.dizitart.no2.NitriteBuilder.openOrCreateInternal(NitriteBuilder.java:387) 
                                                       at org.dizitart.no2.NitriteBuilder.openOrCreate(NitriteBuilder.java:338) 
                                                       at com.example.newtype.nitritetest.MainActivity.startDatabase(MainActivity.java:26) 
                                                       at com.example.newtype.nitritetest.MainActivity.onCreate(MainActivity.java:18) 
                                                       at android.app.Activity.performCreate(Activity.java:6705) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2664) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:241) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6217) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by anidotnet** [comment]
Probably you are targeting JDK 1.6, instead you should try with JDK 1.7 and use the latest android sdk. Can you please try this and let me know?

**Comment by ariel-lenis** [comment]
Thanks to reply.

To use the JDK 1.7 version i added this section to the gradle file (thats what you mean?):

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

This is the build.gradle file:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.newtype.nitritetest"
        minSdkVersion 22
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'org.dizitart:nitrite:1.0'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
}

**Comment by anidotnet** [comment]
Not only that, in your Android studio set the Java SDK location to JDK 1.7 installation. File->Project Structure->SDK location -> JDK location

**Comment by anidotnet** [comment]
If it is resolved please do inform me so that I can close the issue.

**Comment by ariel-lenis** [comment]
I changed the jdk version to 1.8 (android studio says 1.8 as minimum) but the problem was not fixed.

I used this code:

        String appPath = this.getApplication().getApplicationContext().getFilesDir().getAbsolutePath();        

        Nitrite db = Nitrite.builder()
                .compressed()
                .filePath(appPath + "/test.db")
                .openOrCreate("user", "password");

And it works now (without specifying the jdk version, just the default configuration)!!!

Looks like a problem with the folder "/tmp" from the examples because the folder does not exists.

**Comment by anidotnet** [comment]
Glad to hear it is resolved. Yes you are right, quick example code actually is for *nix systems. I am closing the defect now.
