### ISSUE TITLE
Android and Java 8

### ISSUE THREAD

**Issue by Try4W** [dizitart/nitrite-database#51]
Hi!

Google don't include Java 8 Time API in Android's standard library.
How can we deal with? I use `threetenabp` backport, will it work with nitrite?

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
                                             at com.fasterxml.jackson.datatype.jsr310.JavaTimeModule.<init>(JavaTimeModule.java:139)
                                             at org.dizitart.kno2.KNO2JacksonMapper.<init>(KNO2JacksonMapper.kt:35)
                                             at org.dizitart.kno2.Builder.createNitriteBuilder$potassium_nitrite(Builder.kt:114)
                                             at org.dizitart.kno2.BuilderKt.nitrite(Builder.kt:141)
                                             at org.dizitart.kno2.BuilderKt.nitrite$default(Builder.kt:138)
```

**Comment by Try4W** [comment]
This problem could be fixed via using custom nitriteMapper like this:
```
    fun database(): Nitrite = nitrite {
        file = File("database")
        nitriteMapper = object : JacksonMapper() {
            init {
                objectMapper.registerModule(KotlinModule())
                objectMapper.registerModule(ThreetenabpTimeModule())
                objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            }
        }
    }
```

**Comment by anidotnet** [comment]
kno2 already has its own NitriteMapper - [KNO2JacksonMapper](https://github.com/dizitart/nitrite-database/blob/master/potassium-nitrite/src/main/kotlin/org/dizitart/kno2/KNO2JacksonMapper.kt) which is already registered with kno2, so you don't have to do nothing about kotlin data classes and java time api.

But if you are on android, and using backport, then your solution is the way forward.

In next iteration snapshot I am opening up ```KNO2JacksonMapper``` from ```internal``` to ```public``` so that you can extend from it instead of ```JacksonMapper```.

**Comment by anidotnet** [comment]
You can now have it in 2.2.0-SNAPSHOT

**Comment by Jaszczur1337** [comment]
If you could include it in the readme, i wasted so much time on this

**Comment by anidotnet** [comment]
@Jaszczur1337 what do you like me to include in readme?
