### ISSUE TITLE
Сan I add Index for "@type" field generated by jackson?

### ISSUE THREAD

**Issue by Try4W** [dizitart/nitrite-database#67]
```
@Indices(value = arrayOf(
        Index(value = "localId", type = IndexType.NonUnique),
        Index(value = "caObjectLocalId", type = IndexType.NonUnique),
        Index(value = "dateTime", type = IndexType.NonUnique),
        Index(value = "item.@type", type = IndexType.NonUnique)
))
data class CaoHistoryRecord(
        val localId: UUID,
        val caObjectLocalId: UUID,
        val dateTime: LocalDateTime,
        val item: CaoHistoryRecordItem
)
```

```
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "@type")
...
interface CaoHistoryRecordItem
```

```
Caused by: org.dizitart.no2.exceptions.ValidationException: NO2.1074: no such value '@type' for type eu.cortex.cortexalarm.data.daos.caobjectshistory.entities.CaoHistoryRecordItem
```

**Comment by anidotnet** [comment]
Jackson generated fields are not supported.

**Comment by Try4W** [comment]
What about implementing flag `skipValidation` for `Index` annotation?

**Comment by anidotnet** [comment]
Theoretically it is possible, but I am not willing to. This will create room for so many problems. If somebody tries to create index on an array field and skip validation, nitrite will try to create index on array field and corrupt the database.

**Comment by Try4W** [comment]
Hm. Can we rely on actual `Document` rather than `POJO` during the validation?

**Comment by anidotnet** [comment]
There is no type information of field at `Document` label.

**Comment by Try4W** [comment]
Okay, I will try to declare 'type' field explicitly

**Comment by anidotnet** [comment]
That will be the simplest and advisable solution IMO. Explicit but simple. In future,  if you want to migrate your serialization technology (gson, fastjson etc) you will have less headache to worry about :smiley:

**Comment by Try4W** [comment]
There is what I tried to do:

```
@Indices(value = arrayOf(
        Index(value = "localId", type = IndexType.NonUnique),
        Index(value = "caObjectLocalId", type = IndexType.NonUnique),
        Index(value = "dateTime", type = IndexType.NonUnique),
        Index(value = "item._type", type = IndexType.NonUnique)
))
data class CaoHistoryRecord(
        val localId: UUID,
        val caObjectLocalId: UUID,
        val dateTime: LocalDateTime,
        val item: CaoHistoryRecordItem
)
```

```
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "_type")
@JsonSubTypes(
        value = [
            JsonSubTypes.Type(MessageCaoHistoryRecordItem::class, name = CaoHistoryRecordItems.TYPE_ALIEN_MESSAGE_ITEM),
            JsonSubTypes.Type(ActivityCheckAlarmCaoHistoryRecordItem::class, name = CaoHistoryRecordItems.TYPE_ALIEN_ACTIVITY_CHECK_ITEM)
        ]
)
abstract class CaoHistoryRecordItem {
    var _type: String? = null // declared explicitly so NitriteDb can index it
}

data class MessageCaoHistoryRecordItem(
        val caoMessage: CaoMessage
) : CaoHistoryRecordItem()
```

But it leads to exception:
```
04-15 12:39:35.032 23458-23574/eu.cortex.cortexalarm E/JacksonMapper: Error while converting document to object java.lang.IllegalArgumentException: Could not resolve type id 'null' as a subtype of [simple type, class eu.cortex.cortexalarm.data.daos.caobjectshistory.entities.CaoHistoryRecordItem]: known type ids = [activity-check-item, message-item] (for POJO property 'item')
        at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: eu.cortex.cortexalarm.data.daos.caobjectshistory.entities.CaoHistoryRecord["item"])
    	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3738) ~[na:0.0]
    	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3656) ~[na:0.0]
    	at org.dizitart.no2.mapper.JacksonMapper.asObjectInternal(JacksonMapper.java:77) ~[na:0.0]
    	at org.dizitart.no2.mapper.AbstractMapper.asObject(AbstractMapper.java:74) ~[na:0.0]
    	at org.dizitart.no2.objects.DefaultObjectRepository.getById(DefaultObjectRepository.java:211) ~[na:0.0]
    	at eu.cortex.cortexalarm.data.daos.caobjectshistory.CaoHistoryRecordsDao$1.onChange(CaoHistoryRecordsDao.kt:28) ~[na:0.0]
```

**Comment by Try4W** [comment]
And now it works:

```
object CaoHistoryRecordItems {
    const val TYPE_ALIEN_MESSAGE_ITEM = "message-item"
    const val TYPE_ALIEN_ACTIVITY_CHECK_ITEM = "activity-check-item"
}

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "_type")
@JsonSubTypes(
        value = [
            JsonSubTypes.Type(MessageCaoHistoryRecordItem::class, name = CaoHistoryRecordItems.TYPE_ALIEN_MESSAGE_ITEM),
            JsonSubTypes.Type(ActivityCheckAlarmCaoHistoryRecordItem::class, name = CaoHistoryRecordItems.TYPE_ALIEN_ACTIVITY_CHECK_ITEM)
        ]
)
abstract class CaoHistoryRecordItem(var _type: String)

data class MessageCaoHistoryRecordItem(
        val caoMessage: CaoMessage
) : CaoHistoryRecordItem(CaoHistoryRecordItems.TYPE_ALIEN_MESSAGE_ITEM)
```

What I done wrong?

**Comment by Try4W** [comment]
But without this annotations, jackson can't know which type to instantiate.

**Comment by anidotnet** [comment]
Yes you are right. I was only talking about indexing perspective only. But to retrieve this data, jackson requires those information.
