### ISSUE TITLE
Create sync users

### ISSUE THREAD

**Issue by mvysny** [dizitart/nitrite-database#73]
Hi! Thank you very much for your awesome work. The DataGate is up and running, but I do not know how I can create sync users. I tried the following in the mongo console:
```
db.getCollection('no2.datagate.users').insert({ userName: "userId", password: "password", accountNonExpired: true, accountNonLocked: true, credentialsNonExpired: true, enabled: true });
```

Also I tried to create the users via the DataGate client moderation page, but the sync code still fails with

```
16:23:51.714 [ScheduledWorker.NO₂] ERROR org.dizitart.no2.sync.DataGateSyncTemplate - Remote error while getting online status
org.dizitart.no2.exceptions.SyncException: NO2.11020: HTTP/1.1 401 Unauthorized
	at org.dizitart.no2.sync.DataGateSyncTemplate.isOnline(DataGateSyncTemplate.java:180)
	at org.dizitart.no2.sync.SyncService.mergeChanges(SyncService.java:125)
	at org.dizitart.no2.sync.CollectionReplicator.run(CollectionReplicator.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Could you please paste an example how to create an user in DataGate, so that the sync client will work?

```
        val dataGateClient = DataGateClient("http://localhost:9090")
            .withAuth("sa", "sasasa")
        val syncTemplate = DataGateSyncTemplate(dataGateClient, "remote-collection@userId")
```

Also, what does the `remote-collection@userId` parameter mean?

**Comment by mvysny** [comment]
Trying to create a remote user fails with 404:

```
        val dataGateClient = DataGateClient("http://localhost:9090")
            .withAuth("sa5", "sasasa")

        val userAccount = UserAccount()
        userAccount.userName = "sa6"
        userAccount.password = "sasasa"
        userAccount.authorities = arrayOf("USER")
        userAccount.collections = listOf("test@sa6")
//        DataGateUserTemplate(dataGateClient).getUserAccount("sa3")
        DataGateUserTemplate(dataGateClient).createRemoteUser(userAccount)
```

fails with:

```
Exception in thread "main" org.dizitart.no2.exceptions.SyncException: NO2.11003: HTTP/1.1 404 Not Found
	at org.dizitart.no2.sync.DataGateUserTemplate.createRemoteUser(DataGateUserTemplate.java:94)
	at MyMainKt.main(MyMain.kt:62)
```

The error message should be more specific and should provide more information to the cause of the error.

**Comment by mvysny** [comment]
I'm running DataGate 3.0.0 in Docker.

**Comment by mvysny** [comment]
I changed the port from 9090 to 8080 and now it seems to be doing sync. Unfortunately it fails with timeout exception:

```
17:14:06.028 [ScheduledWorker.NO₂] ERROR org.dizitart.no2.sync.DataGateSyncTemplate - Remote error while submitting change feed to remote
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at org.dizitart.no2.sync.DataGateClient$1.intercept(DataGateClient.java:154)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.dizitart.no2.sync.DataGateSyncTemplate.change(DataGateSyncTemplate.java:99)
	at org.dizitart.no2.sync.SyncService.mergeChanges(SyncService.java:235)
	at org.dizitart.no2.sync.SyncService.mergeChanges(SyncService.java:145)
	at org.dizitart.no2.sync.CollectionReplicator.run(CollectionReplicator.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 33 common frames omitted
17:14:06.028 [ScheduledWorker.NO₂] ERROR org.dizitart.no2.sync.SyncService - Replication error
org.dizitart.no2.exceptions.SyncException: NO2.11011: error while submitting changes to remote collection
	at org.dizitart.no2.sync.DataGateSyncTemplate.change(DataGateSyncTemplate.java:109)
	at org.dizitart.no2.sync.SyncService.mergeChanges(SyncService.java:235)
	at org.dizitart.no2.sync.SyncService.mergeChanges(SyncService.java:145)
	at org.dizitart.no2.sync.CollectionReplicator.run(CollectionReplicator.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at org.dizitart.no2.sync.DataGateClient$1.intercept(DataGateClient.java:154)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.dizitart.no2.sync.DataGateSyncTemplate.change(DataGateSyncTemplate.java:99)
	... 10 common frames omitted
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 33 common frames omitted
```

**Comment by anidotnet** [comment]
Currently I am traveling and commenting from my mobile. Once I get hold of my desktop, I'll look into the code and give you some insight. Meanwhile if possible share me the log file for datagate and nitrite.

**Comment by anidotnet** [comment]
Please try with setting larger read timeout in`DataGateClient` using [readTimeout](https://github.com/dizitart/nitrite-database/blob/master/nitrite/src/main/java/org/dizitart/no2/sync/DataGateClient.java#L100).

**Comment by anidotnet** [comment]
Any progress on it yet?

**Comment by mvysny** [comment]
Thank you @anidotnet and sorry for the delay. That setting indeed helped :+1:

**Comment by mvysny** [comment]
The document is really tiny, just one mapping from "animal" to "cat26"; it's just a testing database with 10000 of such tiny documents.

**Comment by anidotnet** [comment]
I am closing this issue now as the Socket timeout issue is resolved. Feel free to open another if you face any other issue.

**Comment by mvysny** [comment]
Of course. Thank you very much for your tip with the `readTimeout`

**Comment by dustin-auby** [comment]
Ok what should i be setting it too i have tried 1000, 5000 and 100000 with no success
