### ISSUE TITLE
boolean java.util.concurrent.atomic.AtomicBoolean.get()' on a null object reference

### ISSUE THREAD

**Issue by ArthurSav** [dizitart/nitrite-database#77]
Happens in an async task. I try to delete everything in a Repository and then re-insert a new list of objects - not sure how to reproduce.

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.atomic.AtomicBoolean.get()' on a null object reference
       at org.dizitart.no2.internals.IndexingService.removeIndexEntry(IndexingService.java:152)
       at org.dizitart.no2.internals.DataService.remove(DataService.java:227)
       at org.dizitart.no2.internals.NitriteService.remove(NitriteService.java:372)
       at org.dizitart.no2.internals.DefaultNitriteCollection.remove(DefaultNitriteCollection.java:360)
       at org.dizitart.no2.objects.DefaultObjectRepository.remove(DefaultObjectRepository.java:176)
       at org.dizitart.no2.objects.DefaultObjectRepository.remove(DefaultObjectRepository.java:170)
       at io.app.Database.deleteUserStats(Database.java:258)
       at io.app.Database.saveUserStats(Database.java:198)
       at io.app.async.StatsSync.doInBackground(StatsSync.java:39)
       at io.app.async.StatsSync.doInBackground(StatsSync.java:13)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)`

**Comment by anidotnet** [comment]
@ArthurSav the latest snapshot should have the fix for it.
