### ISSUE TITLE
Error when tried execute on Android App

### ISSUE THREAD

**Issue by ericbbraga** [dizitart/nitrite-database#90]
I'm trying to use nitrite database on my Android app. However, when I compiled and run my app one exception Occurred

> java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/ws/Holder;
                      at uk.co.jemos.podam.api.PodamFactoryImpl.fillCollection(PodamFactoryImpl.java:1209)
                      at uk.co.jemos.podam.api.PodamFactoryImpl.resolveCollectionValueWhenCollectionIsPojoAttribute(PodamFactoryImpl.java:1080)
                      at uk.co.jemos.podam.api.PodamFactoryImpl.manufactureAttributeValue(PodamFactoryImpl.java:942)
                      at uk.co.jemos.podam.api.PodamFactoryImpl.manufactureParameterValue(PodamFactoryImpl.java:1908)
                      at uk.co.jemos.podam.api.PodamFactoryImpl.getParameterValuesForConstructor(PodamFactoryImpl.java:1769)
                      at uk.co.jemos.podam.api.PodamFactoryImpl.instantiatePojo(PodamFactoryImpl.java:383)
                      at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojoInternal(PodamFactoryImpl.java:506)
                      at uk.co.jemos.podam.api.PodamFactoryImpl.doManufacturePojo(PodamFactoryImpl.java:429)
                      at uk.co.jemos.podam.api.PodamFactoryImpl.manufacturePojo(PodamFactoryImpl.java:151)
                      at org.dizitart.no2.util.DocumentUtils.dummyDocument(DocumentUtils.java:139)
                      at org.dizitart.no2.util.DocumentUtils.emptyDocument(DocumentUtils.java:105)
                      at org.dizitart.no2.objects.ObjectCursor.project(ObjectCursor.java:53)

**Comment by ericbbraga** [comment]
I've found in Podam that it is a issue on this library.
Please check the link - https://github.com/mtedone/podam/issues/264

**Comment by anidotnet** [comment]
Putting it on hold as podam 7.2.0 is not released yet.

**Comment by mjustin** [comment]
Note that you could add a dependency on javax.xml.ws:jaxws-api:2.3.0 as a workaround until PODAM 7.2.0 is released (either within nitrite or within the app that's using nitrite).

**Comment by anidotnet** [comment]
This fix should be available in 3.1.0-SNAPSHOT
